spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/milktea?useSSL=false&serverTimezone=UTC
    username: milktea
    password: 1111
    hikari:
      maximum-pool-size: 10       # max connections in the pool
      minimum-idle: 5             # minimum idle connections in the pool
      idle-timeout: 30000         # idle timeout in milliseconds
      max-lifetime: 1800000       # max lifetime of a connection in milliseconds
      connection-timeout: 20000   # timeout for a connection in milliseconds
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      database: 1
      username: milktea
      password: 1111